# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sun_tzu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(unique=True)),
                ('player_one', models.CharField(max_length=256)),
                ('player_two', models.CharField(max_length=256)),
            ],
        ),
    ]
