# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sun_tzu', '0002_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('player_control', models.CharField(default='', max_length=256)),
                ('round_one_points', models.IntegerField()),
                ('round_two_points', models.IntegerField()),
                ('round_three_points', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='province',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sun_tzu.Game'),
        ),
    ]
