# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sun_tzu', '0002_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='player',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
