# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sun_tzu', '0003_auto_20171102_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='sun_tzu.UserProfileInfo'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='sun_tzu.UserProfileInfo'),
        ),
    ]
