# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sun_tzu', '0004_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='armies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='province',
            name='player_one_card',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='province',
            name='player_two_card',
            field=models.CharField(default='', max_length=3),
        ),
    ]
