# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sun_tzu', '0005_auto_20171104_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='turns_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.IntegerField(default=1),
        ),
    ]
