# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sun_tzu', '0005_auto_20171102_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
