# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sun_tzu', '0007_player_played_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='phase',
            field=models.IntegerField(default=0),
        ),
    ]
