# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sun_tzu', '0009_auto_20171106_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='played_six',
            field=models.BooleanField(default=False),
        ),
    ]
