# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sun_tzu', '0010_province_played_six'),
    ]

    operations = [
        migrations.RenameField(
            model_name='province',
            old_name='played_six',
            new_name='player_one_played_six',
        ),
        migrations.AddField(
            model_name='province',
            name='player_two_played_six',
            field=models.BooleanField(default=False),
        ),
    ]
