# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sun_tzu', '0011_auto_20171106_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='player_one_last_card',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='province',
            name='player_two_last_card',
            field=models.CharField(default='', max_length=3),
        ),
    ]
