# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sun_tzu', '0012_auto_20171107_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='sun_tzu.UserProfileInfo'),
            preserve_default=False,
        ),
    ]
