# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sun_tzu', '0015_game_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
